apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hellow
  template:
    metadata:
      labels:
        app: hellow
    spec:
      containers:
      - name: hellow
        image: mcr.microsoft.com/azuredocs/aks-helloworld:v1
        ports:
        - containerPort: 80
        env:
        - name: TITLE
          value: "Hellow Wlopezob"

---
apiVersion: v1
kind: Service
metadata:
  name: hellow
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: hellow
